// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"context"
)

type Querier interface {
	GetMeetingCount(ctx context.Context, name string) (int32, error)
	IncrementMeetingCount(ctx context.Context, name string) error
}

var _ Querier = (*Queries)(nil)
